#!/bin/bash

valip() {
      local ip=$1
      local stat=1
      if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
      fi
      return $stat
}

subd(){
 [[ ! -z ${callback_query_message_chat_id[$id]} ]] && {
	var=${callback_query_message_chat_id[$id]}
 } || {
	var=${message_chat_id[$id]}
 }
subdlog=$fsub
[[ ! -e $subdlog ]] && touch $subdlog
datauser
unset bot_retorno data
local bsb='' data=($@)
if [[ -z $2 ]]; then
	error='FALTA EL SUBDOMINIO'
	if [[ -z $1 ]]; then
		error='FALTA IP Y SUBDOMINIO'
	fi
	bot_retorno="$line\n<b>${error}</b>\n$line\n"
	bot_retorno+="     <b>Lista de dominios disponibles:</b>\n$line\n"
	bot_retorno+=" ${space}[01] alawistore.my.id\n${space} [02] alawistore.biz.id\n${space} [03] alawivpn.cloud\n${space} [04] cakdayat.my.id\n${space} [05] petapan.my.id\n${space} [06] sayasantri.my.id\n${space} [07] serverssh.biz.id\n${space} [08] sshserver.my.id\n${space} [09] udpserver.my.id\n${space} [10] vmesserver.my.id\n${space} [11] vpnbagus.my.id  \n${space} [12] vpnssh.biz.id   \n${space} [13] vpssantri.my.id \n${space} [14] vpsvpn.my.id\n${space} [15] wush.my.id\n${space} [16] wussh.my.id \n$line\n Selecciona un dominio y crea tu subdominio apartir del mismo.\n\n Ejemplo:  <code>eseldrowkid01.my.id</code> ó <code>eselkidpa.vpssantri.my.id</code>\n$line\n"
	menu_print 'atras'&&return $?
fi
if((${#@}));then
	local ip=${data[0]}
	local subd[1]=${data[1]/./@} subd[0]=${data[1]}
	local var1=$(echo ${subd[1]}|awk -F "@" '{print $2}')

	if valip "${data[0]}" ; then
		unset ip&&ip="${data[0]}"
	else
		bot_retorno="$line\n❌<b>IP ${data[0]} INVÁLIDA</b>❌\n$line\n"
		menu_print 'atras'&&return $?
	fi

	case $var1 in
		'alawistore.my.id'|'alawistore.biz.id'|'alawivpn.cloud'|'cakdayat.my.id'|'petapan.my.id'|'sayasantri.my.id'|'serverssh.biz.id'|'sshserver.my.id'|'udpserver.my.id'|'vmesserver.my.id'|'vpnbagus.my.id'|'vpnssh.biz.id'|'vpssantri.my.id'|'vpsvpn.my.id')domain="$var1";;
		*)unset domain;;
	esac
	if [[ -z $domain ]]; then
		bot_retorno="$line\n     ❌ ELIGE UN DOMINIO DE LA LISTA Y PARTIENDO DEL MISMO, CREA TU SUBDOMINIO ❌\n$line\n"
		msj_fun&&sleep 2
		datauser
		bot_retorno+="     <b>Lista de dominios disponibles:</b>\n$line\n"
		bot_retorno+=" ${space}[01] alawistore.my.id\n${space} [02] alawistore.biz.id\n${space} [03] alawivpn.cloud\n${space} [04] cakdayat.my.id\n${space} [05] petapan.my.id\n${space} [06] sayasantri.my.id\n${space} [07] serverssh.biz.id\n${space} [08] sshserver.my.id\n${space} [09] udpserver.my.id\n${space} [10] vmesserver.my.id\n${space} [11] vpnbagus.my.id  \n${space} [12] vpnssh.biz.id   \n${space} [13] vpssantri.my.id \n${space} [14] vpsvpn.my.id\n${space} [15] wush.my.id\n${space} [16] wussh.my.id \n$line\n Selecciona un dominio y crea tu subdominio apartir del mismo.\n\n Ejemplo:  <code>eseldrowkid01.my.id</code> ó <code>eselkidpa.vpssantri.my.id</code>\n$line\n"
		menu_print 'atras'
		return $?
	else
		if [[ $(cat $subdlog|grep "${subd[0]}") ]]; then
			bot_retorno="$line\n❌ EL SUBDOMINIO: ${subd[0]} YA ES UTILIZADO POR OTRO USUARIO ❌\n$line\n<b>¡reintenta de nuevo @${usrname}!</b>\n$line\n"
			menu_print 'atras'&&return $?
		else
			datauser
			bot_retorno+="  <b>[~] ENLAZAR IP => SUBDOMAIN [~]</b>\n\n<ins>IP:</ins> <tg-spoiler>$ip</tg-spoiler>\n<ins>Dominio:</ins> $domain\n<ins>Subdominio:</ins> <code>${subd[0]}</code>\n$line\n⚡Powered by: @drowkid01⚡\n$line\n"

			ShellBot.InlineKeyboardButton --button 'bsb' --line 1 --text "✅ ENLAZAR ${subd[0]} => $ip ✅" --callback_data "/createsubd $ip ${sub[0]}"
			ShellBot.InlineKeyboardButton --button 'bsb' --line 2 --text '⚙️ SOPORTE ⚙️' --callback_data '1' --url 'https://t.me/drowkid01'
			ShellBot.InlineKeyboardButton --button 'bsb' --line 3 --text '<<< volver al menú anterior' --callback_data '/menu'

			ShellBot.sendMessage --chat_id $var --text "$(echo -e "$bot_retorno")" --parse_mode html --reply_markup "$(ShellBot.InlineKeyboardMarkup -b 'bsb')"
		fi
	fi
else
	return $?
fi
}

domain-IP(){
local subd=''
fsubd=$fsub
[[ ! -e $fsubd ]] && touch $fsubd
numsubd=$(cat $fsubd|wc -l)
[[ -z $numsubd ]] && numsubd=0
  [[ -z $1 ]] && {
	[[ ! -z ${callback_query_message_chat_id[$id]} ]] && var=${callback_query_message_chat_id[$id]} || var=${message_chat_id[$id]}
	space='         '
	bot_retorno="$line\n               [~] <b>SUBDOMAINS => IP </b> [~]\n$line\n"
	bot_retorno+="\n<b>Subdominios:</b>  $numsubd\n\n$line\n"
	bot_retorno+="<b>Modo de uso:</b>\n\nSólamente necesitas ingresar una IP y colocar un subdominio creado apartir de la lista de dominios disponibles.\n$line\n"
	ShellBot.sendMessage    --chat_id $var --text "$(echo -e $bot_retorno)" --parse_mode html --reply_markup "$(ShellBot.InlineKeyboardMarkup -b 'domain')"
  } || {
	case $1 in
	-ip)bot_retorno="$line\n         [•] INGRESA LA IP DE TU VPS [•]\n$line\n"
	msj_fun&&unset bot_retorno&&bot_retorno="${txt[0]}"&&reply;;
	"${txt[0]}")
		datauser
		if valip "${message_text[$id]}"; then
			unset ip
			ip="${message_text[$id]}"&&space='           '
			bot_retorno+="     <b>Lista de subdominios disponibles:</b>\n$line\n"
			bot_retorno+=" ${space}[01] alawistore.my.id\n${space} [02] alawistore.biz.id\n${space} [03] alawivpn.cloud\n${space} [04] cakdayat.my.id\n${space} [05] petapan.my.id\n${space} [06] sayasantri.my.id\n${space} [07] serverssh.biz.id\n${space} [08] sshserver.my.id\n${space} [09] udpserver.my.id\n${space} [10] vmesserver.my.id\n${space} [11] vpnbagus.my.id  \n${space} [12] vpnssh.biz.id   \n${space} [13] vpssantri.my.id \n${space} [14] vpsvpn.my.id\n${space} [15] wush.my.id\n${space} [16] wussh.my.id \n$line\n Selecciona un dominio y crea tu subdominio apartir del mismo.\n\n Ejemplo:  <code>eseldrowkid01.my.id</code> ó <code>eselkidpa.vpssantri.my.id</code>\n$line\n"
			msj_fun&&unset bot_retorno
			bot_retorno="${txt[1]}"&&reply
		else
			bot_retorno="$line\n❌ LA IP: ${message_text[$id]} ES INVÁLIDA! ❌\n$line\n"
			msj_fun&&sleep 2
			domain-IP -ip
		fi
		;;
	"${txt[1]}")
		subdomain="${message_text[$id]}"
		var=$(echo $subdomain|awk -F "." '{print $2}')
		case $var in
			"alawistore"|"alawistore"|"alawivpn"|"cakdayat"|"petapan"|"sayasantri"|"serverssh"|"sshserver"|"udpserver"|"vmesserver"|"vpnbagus"|"vpnssh"|"vpssantri"|"vpsvpn"|"wush"|"wussh")valuesubd="✅ SUBDOMINIO $value VÁLIDO ✅";;
			*)unset valuesubd;;
		esac

		if [[ -z $valuesubd ]]; then
			bot_retorno="$line\n❌<b> ¡EL SUBDOMINIO: <tg-spoiler>$subdomain</tg-spoiler> NO FORMA PARTE DE LA LISTA DE DOMINIOS DISPONIBLES, ELIGE UNO DE LA LISTA! ❌</b>\n$line\n"
			msj_fun&&sleep 2&&datauser
			bot_retorno+="     <b>Lista de subdominios disponibles:</b>\n$line\n"
			bot_retorno+=" ${space}[01] alawistore.my.id\n${space} [02] alawistore.biz.id\n${space} [03] alawivpn.cloud\n${space} [04] cakdayat.my.id\n${space} [05] petapan.my.id\n${space} [06] sayasantri.my.id\n${space} [07] serverssh.biz.id\n${space} [08] sshserver.my.id\n${space} [09] udpserver.my.id\n${space} [10] vmesserver.my.id\n${space} [11] vpnbagus.my.id  \n${space} [12] vpnssh.biz.id   \n${space} [13] vpssantri.my.id \n${space} [14] vpsvpn.my.id\n${space} [15] wush.my.id\n${space} [16] wussh.my.id \n$line\n Selecciona un dominio y crea tu subdominio apartir del mismo.\n\n Ejemplo:  <code>eseldrowkid01.my.id</code> ó <code>eselkidpa.vpssantri.my.id</code>\n$line\n"
			msj_fun&&bot_retorno='Ingresa otro subdominio:'&&reply
			return $?
		fi

		if [[ $(cat $fsubd|grep "$subdomain") ]]; then
			bot_retorno="$line\n❌ <b>EL SUBDOMINIO: <code>$subdomain</code>  YA ES UTILIZADO POR OTRO USUARIO!, INGRESE UNO DISTINTO </b>❌\n$line\n"
			msj_fun&&unset bot_retorno&&unset subdomain
			bot_retorno='Ingresa otro subdominio:'&&reply
		else
			unset bot_retorno&&datauser
			bot_retorno+="          [•] <b>ENLAZAR SUBDOMAIN => IP [•]</b>\n$line\nIP: $ip\nSubdominio: $subdomain\n$line\n<ins><b>¿los datos son correctos?</b></ins>\n$line\n"
			[[ ! -z ${callback_query_message_chat_id[$id]} ]] && var=${callback_query_message_chat_id[$id]} || var=${message_chat_id[$id]}

			ShellBot.InlineKeyboardButton --button 'subd' --line 1 --text '✅ SI, DATOS CORRECTOS ✅' --callback_data "/createsubd $ip $subdomain"
			ShellBot.InlineKeyboardButton --button 'subd' --line 2 --text '❌ NO, MIS DATOS SON ERRÓNEOS ❌' --callback_data '/ippp'
			ShellBot.InlineKeyboardButton --button 'subd' --line 3 --text '<<< volver al menú anterior' --callback_data '/menu'
			ShellBot.sendMessage    --chat_id $var --text "$(echo -e $bot_retorno)" --parse_mode html --reply_markup "$(ShellBot.InlineKeyboardMarkup -b 'subd')"
		fi
	;;
	esac
 }
}

createsubd(){
fsubd=$fsub&&space='       '
ipP=$1
sub1=$2
subdomain="$(echo $sub1|awk -F "." '{print $1}')."
DOMAIN16=${sub1##$subdomain}

SUB_DOMAIN16=${sub1}
SUB_DOMAIN016=zoomcares.zoom.us.${sub1}
CF_ID=vpsvpsku@gmail.com
CF_KEY=cb9b858e75a955df979cf4bff74839df1943d
IP1=$ipP

ZONE=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DOMAIN16}&status=active" \
-H "X-Auth-Email: ${CF_ID}" \
-H "X-Auth-Key: ${CF_KEY}" \
-H "Content-Type: application/json" | jq -r .result[0].id)
RECORD=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${SUB_DOMAIN16}" \
-H "X-Auth-Email: ${CF_ID}" \
-H "X-Auth-Key: ${CF_KEY}" \
-H "Content-Type: application/json" | jq -r .result[0].id)
if [[ "${#RECORD}" -le 10 ]]; then
RECORD=$(curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
-H "X-Auth-Email: ${CF_ID}" \
-H "X-Auth-Key: ${CF_KEY}" \
-H "Content-Type: application/json" \
--data '{"type":"A","name":"'${SUB_DOMAIN16}'","content":"'${IP1}'","ttl":120,"proxied":false}' | jq -r .result.id)
fi
RESULT=$(curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
-H "X-Auth-Email: ${CF_ID}" \
-H "X-Auth-Key: ${CF_KEY}" \
-H "Content-Type: application/json" \
--data '{"type":"A","name":"'${SUB_DOMAIN16}'","content":"'${IP1}'","ttl":120,"proxied":false}')
#zoomcares.zoom.us
ZONE=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DOMAIN16}&status=active" \
-H "X-Auth-Email: ${CF_ID}" \
-H "X-Auth-Key: ${CF_KEY}" \
-H "Content-Type: application/json" | jq -r .result[0].id)
RECORD=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${SUB_DOMAIN016}" \
-H "X-Auth-Email: ${CF_ID}" \
-H "X-Auth-Key: ${CF_KEY}" \
-H "Content-Type: application/json" | jq -r .result[0].id)
if [[ "${#RECORD}" -le 10 ]]; then
RECORD=$(curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
-H "X-Auth-Email: ${CF_ID}" \
-H "X-Auth-Key: ${CF_KEY}" \
-H "Content-Type: application/json" \
--data '{"type":"A","name":"'${SUB_DOMAIN016}'","content":"'${IP1}'","ttl":120,"proxied":false}' | jq -r .result.id)
fi
RESULT=$(curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
-H "X-Auth-Email: ${CF_ID}" \
-H "X-Auth-Key: ${CF_KEY}" \
-H "Content-Type: application/json" \
--data '{"type":"A","name":"'${SUB_DOMAIN016}'","content":"'${IP1}'","ttl":120,"proxied":false}')


datauser
echo -e "$ipP|$sub1|$var" >> $fsubd

bot_retorno+="${space}🚀 DETALLES DEL PROCESO🚀\n$line\n"
bot_retorno+="${space}🌐 ●⸺[ <b>DOMINIO:</b> <tg-spoiler>$DOMAIN16</tg-spoiler> ]\n"
bot_retorno+="${space}🆓 ●⸺[ <b>SUBDOMINIO:</b> <tg-spoiler>$sub1</tg-spoiler> ]\n"
bot_retorno+="${space}📍 ●⸺[ <b>IP:</b> <tg-spoiler>$IP1</tg-spoiler> ]\n"
bot_retorno+="$line\n✅ <b>SUBDOMINIO CREADO EXITOSAMENTE</b> ✅\n"
bot_retorno+="$line\n    ⚡ powered by @drowkid01 ⚡\n$line\n"

menu_print 'atras'
}


checkey(){
scpinst="`pwd`/scpinstal"
scpdir="`pwd`/adm-dkid"

ofu() {
unset txtofus
number=$(expr length $1)
for((i=1; i<$number+1; i++)); do
txt[$i]=$(echo "$1" | cut -b $i)
case ${txt[$i]} in
".") txt[$i]="x";;
"x") txt[$i]=".";;
"5") txt[$i]="s";;
"s") txt[$i]="5";;
"1") txt[$i]="@";;
"@") txt[$i]="1";;
"2") txt[$i]="?";;
"?") txt[$i]="2";;
"4") txt[$i]="0";;
"0") txt[$i]="4";;
"/") txt[$i]="K";;
"K") txt[$i]="/";;
esac
txtofus+="${txt[$i]}"
done
echo "$txtofus" | rev
}

verify(){
  [[ -e ${scpinst}/$1 ]] && {
	mv -f ${scpinst}/$1 ${scpdir}/$1
	chmod +x ${scpdir}/$1
  }
}

case $1 in
 -k) #unset bot_retorno
	bot_retorno='Ingrese su key:'&&reply;;
 -p |'Ingrese su key:')
	Key=$(echo "${message_text[$id]}"|tr -d '[[:space:]]')
	cd $HOME
	IiP=$(ofu "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
	[[ $(curl -s --connect-timeout 5 $IiP:8888 ) ]] && {
		datauser
		bot_retorno+=" 🔐 <b>VERIFICANDO KEY</b> 🔐\n"
		ofen=$(wget -qO- $(ofu $Key))
		ip=$(ofu "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
		wget --no-check-certificate -O $HOME/lista-arq $(ofu "$Key")/$ip > /dev/null 2>&1
	} || {
	      bot_retorno="❌ERROR DE CONEXIÓN❌"
	}
	msj_fun
	if [[ ! $(cat $HOME/lista-arq|grep 'KEY INVALIDA!') ]]; then
		[[ -e $HOME/log.txt ]] && rm -f $HOME/log.txt
		MSG_id=$((${message_message_id} + 1 ))
		#msj_del ${message_message_id}&&msj_del ${MSG_id}
		   IP=$(ofu "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
		   REQUEST=$(ofu "$Key"|cut -d'/' -f2)
		   [[ ! -d ${scpdir} ]] && mkdir ${scpdir} || rm -f ${scpdir}/*
		   [[ ! -d ${scpinst} ]] && mkdir ${scpinst} || rm -f ${scpinst}/*
		for arqx in $(cat $HOME/lista-arq); do
			wget --no-check-certificate -O ${scpinst}/${arqx} ${IP}:81/${REQUEST}/${arqx} > /dev/null 2>&1 && verify "${arqx}"
		done
		datauser
		bot_retorno+="✅ KEY VÁLIDA ✅\n$line\nFILES: <tg-spoiler>$(ls ${scpdir}|xargs)</tg-spoiler>\n$line"
		menu_print 'atras'
	fi
;;
esac
}

checkeY(){
unset -f ofuz
ofuz() {
                unset server
                server=$(echo ${txt_ofuscatw}|cut -d':' -f1)
                unset txtofus
                number=$(expr length $1)
                for((i=1; i<$number+1; i++)); do
                txt[$i]=$(echo "$1" | cut -b $i)
                case ${txt[$i]} in
                        ".")txt[$i]="C";;
                        "C")txt[$i]=".";;
                        "3")txt[$i]="@";;
                        "@")txt[$i]="3";;
                        "5")txt[$i]="9";;
                        "9")txt[$i]="5";;
                        "6")txt[$i]="D";;
                        "D")txt[$i]="6";;
                        "J")txt[$i]="Z";;
                        "Z")txt[$i]="J";;
                esac
                txtofus+="${txt[$i]}"
                done
                echo "$txtofus" | rev
        }
case $1 in
 -k)bot_retorno='Ingrese su key:'
	reply;;
 -p|'Ingrese su key:')
	key=$(echo ${message_text[$id]}|tr -d '[[:space:]]')
	IiP=$(ofus "$key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
	[[ $(curl -s --connect-timeout 5 $IiP:8888 ) ]] && {
		bot_retorno="✅ VERIFICANDO CONEXIÓN ✅\n"
		msj_fun&&sleep 2
		MSG_id=$((${message_message_id} + 1 ))
		msj_del ${message_message_id}&&msj_del ${MSG_id}
		ip=$(ofus "$key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
		wget --no-check-certificate -O $HOME/lista-arq $(ofus "$key")/$ip > /dev/null 2>&1
		bot_retorno="✅ LISTA-ARQ OBTENIDA ✅"
	} || {
	      bot_retorno="❌ERROR DE CONEXIÓN❌"
	}

	msj_fun&&unset bot_retorno

	if [[ ! $(cat $HOME/lista-arq|grep 'KEY INVALIDA!') ]]; then
		[[ -e $HOME/log.txt ]] && rm -f $HOME/log.txt
		IP=$(ofus "$key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
		   REQUEST=$(ofus "$key"|cut -d'/' -f2)
		   scpinst="`pwd`/scpinstal"
		   [[ ! -d ${scpdir} ]] && mkdir ${scpdir} || rm -f ${scpdir}/*
		   [[ ! -d ${scpinst} ]] && mkdir ${scpinst} || rm -f ${scpinst}/*
		for arqx in $(cat $HOME/lista-arq); do
			wget --no-check-certificate -O ${scpinst}/${arqx} ${IP}:81/${REQUEST}/${arqx} > /dev/null 2>&1
		done
	fi
	MSG_id=$((${message_message_id} + 1 ))
	msj_del ${message_message_id}&&msj_del ${MSG_id}
	bot_retorno="$line\n✅ KEY VÁLIDA ✅\n$line\nFiles: $(ls $scpinst|xargs)\n$line\n"
	rm -rf ${scpinst} ${scpdir} $HOME/lista-arq
	menu_print 'atras';;
esac
}
